version: '2'

volumes:
  mongodb-data:

services:

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: octofarm
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    restart: always

  octofarm:
    #image: thetinkerdad/octofarm:latest
    build: .
    container_name: octofarm
    environment:
      MONGOHOST: mongodb
      MONGOUSER: root
      MONGOPASS: rootpassword
    ports:
      - 4000:4000
    volumes:
#      - ${PWD}/logs/production.log:/var/lib/octofarm/production.log
#      - ${PWD}/logs/productionError.log:/var/lib/octofarm/productionError.log
      - ${PWD}/logs/additional/:/root/.npm/_logs/
    restart: always
